### ISSUE TITLE
Addon is not compatible with a recent Kodi

### ISSUE THREAD

**Issue by samm-git** [waladir/plugin.audio.cro#1]
Hi,
While trying to run on v20 i am getting message about incompatibility, addon is failing to load

Update: install from master works, so would be nice to have it updated

**Comment by waladir** [comment]
Hi,

please check version of XBMC-Kodi CZ/SK repository, what should be 1.3.0 (for Kodi Nexus) and try reinstall addon from this repository. Issue could be caused by using repo for Kodi Leia what is different than version for Matrix/Nexus.

W.

**Comment by samm-git** [comment]
@waladir thank you for reply (and for addon, of course!). Somehow i had old (python 2.4) extension installed, i just re-installed it from this repo using zip file, and all works fine again. Thanks again and apologize for the false report :)
